### ISSUE TITLE
TypeError bug

### ISSUE THREAD

**Issue by jhao104** [deslum/cssdbpy#14]
```
>>> from cssdbpy import Connection
>>> conn = Connection('127.0.0.1', 8888)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cssdbpy/cssdbpy.pyx", line 20, in cssdbpy.cssdbpy.Connection.__init__ (cssdbpy/cssdbpy.c:1029)
TypeError: Expected bytes, got str
```

**Comment by deslum** [comment]
you are using the latest version?
please try 

`Connection('127.0.0.1', '8888')`

but I will fix this bug

**Comment by jhao104** [comment]
it's work! 
tks
