### ISSUE TITLE
Support for password authentication ?

### ISSUE THREAD

**Issue by jhao104** [deslum/cssdbpy#7]
hello, 
thanks  for share nice tool.
does this  library support password authentication?

**Comment by deslum** [comment]
Hello.

Yes, support. For simple example https://gist.github.com/deslum/c31f1fe1a7c8ad0aa1459454bd7dfcd9
But when you are not authorized to show an error. I'll fix it.

Thanks for issue.

**Comment by deslum** [comment]
Error if not auth

```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    print conn.execute('hset', 'test', "one", "1")
  File "cssdbpy/cssdbpy.pyx", line 34, in cssdbpy.cssdbpy.Connection.execute (cssdbpy/cssdbpy.c:1609)
  File "cssdbpy/cssdbpy.pyx", line 43, in cssdbpy.cssdbpy.Connection._read (cssdbpy/cssdbpy.c:1745)
  File "cssdbpy/cssdbpy.pyx", line 58, in cssdbpy.cssdbpy.Connection._parse (cssdbpy/cssdbpy.c:2038)
TypeError: Expected list, got str
```
Authorization works

**Comment by jhao104** [comment]
Thanks for explain :smiley:

**Comment by deslum** [comment]
Bug fix. Client answer if not auth

`['authentication required', '']`

**Comment by deslum** [comment]
If you find errors, then write to me, open new issues. I really appreciate your feedback
